### ISSUE TITLE
Redesign Items that do not work

### ISSUE THREAD

**Issue by Doug-Bowen** [Doug-Bowen/BindingOfIsaacMod-TheGarden#18]
See: https://github.com/Doug-Bowen/isaacMods/blob/master/README.md 

Shame - works as intended
Forbidden Fruit - knockback cannot be applied currently
Deception - I might be able to shuffly pills, not sure though (doubtful)
Granted Domain - WIll simply apply freeze to anythign in the room when isaac isnt moving (so they will stop firing too)
The Will of Man - Super tricky, but it might actualyl be able to do it.
The Fall of Man - since i cannot change item pools, this item is not possible
Rebirth - i believe changing characters is possible through the API, i juist havent done it yet
The First Day - should be fine
Exiled - I can neither alter item pools. I do not think i can apply champion belt affect either. 
Miracle Grow - I cannot include this within the treasure pool (item rooms) and i have no access to floor generation.

**Comment by RobertDeSonier** [comment]
Miracle Grow - can you change room % chance?
@Doug-Bowen

**Comment by Doug-Bowen** [comment]
Doesn't look like it? I can use Room:GetSpawnSeed() to returns an integer that was used to generate a garden however it has no documentation so I'm not sure if that's even the right direction.

https://moddingofisaac.com/docs/class_room.html#a8f041df37fe23e38950c58358134f987

EDIT: There is also Level::GetDungeonPlacementSeed()
https://moddingofisaac.com/docs/class_level.html#a07c2dac108d5bfb25b5398ff0c749797

**Comment by RobertDeSonier** [comment]
Exiled - You should be able to apply Champion Belt effect:
https://moddingofisaac.com/docs/class_temporary_effects.html#a225fd65e951189f3cc96ebbda4a19e40

**Comment by Doug-Bowen** [comment]
Awesome find!

**Comment by Doug-Bowen** [comment]
Miracle Grow was changed to My Beloved. +1 Heart container, all hearts (of all types) will slowly gravitate towards isaac until he picks them up.
